disabled_rules:
  - line_length

opt_in_rules:
  - array_init
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - colon
  - comma
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_enum_raw_value
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - let_var_whitespace
  - literal_expression_end_indentation
  - mark
  - multiline_arguments
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - number_separator
  - object_literal
  - opening_brace
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_over_fileprivate
  - prohibited_super_call
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_void_return
  - return_arrow_whitespace
  - single_test_class
  - sorted_first_last
  - statement_position
  - strict_fileprivate
  - switch_case_on_newline
  - trailing_closure
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - unneeded_parentheses_in_closure_argument
  - unused_closure_parameter
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
